### ISSUE TITLE
Feature request: custom policies

### ISSUE THREAD

**Issue by Sebastix** [nostriphant/transpher#16]
Many relay implementions provide a way to configure a custom policy where you can define what the relay should do (accept/reject) with client requests.

Some examples:
* https://github.com/cameri/nostream/blob/main/CONFIGURATION.md#settings
* https://pkg.go.dev/github.com/fiatjaf/khatru@v0.9.1/policies
* https://git.sr.ht/~gheartsfield/nostr-rs-relay/tree/HEAD/config.toml#L107
* https://github.com/hoytech/strfry/blob/master/docs/plugins.md
* https://github.com/fiatjaf/jingle

I haven't digged through the whole codebase (yet) but I would love to see this in the current implementation. 

Any feedback on this topic is welcome while I will try to find some time to make a first proposal for this.

**Comment by rikmeijer** [comment]
Excellent idea, will look into this!👀

**Comment by rikmeijer** [comment]
Working first from 
https://github.com/cameri/nostream/blob/main/CONFIGURATION.md#settings seeing that's a nice list. Splitting it out in several, coherent issues.

# NIP-11, already implemented
|   |                           Name                           |                                                           Description                                                          |
|---|:--------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------:|
| ✅ | info.relay_url                                           | Public-facing URL of your relay. (e.g. wss://relay.your-domain.com)                                                            |
| ✅ | info.name                                                | Public name of your relay. (e.g. TBG's Public Relay)                                                                           |
| ✅ | info.description                                         | Public description of your relay. (e.g. Toronto Bitcoin Group Public Relay)                                                    |
| ✅ | info.pubkey                                              | Relay operator's Nostr pubkey in hex format.                                                                                   |
| ✅ | info.contact                                             | Relay operator's contact. (e.g. mailto:operator@relay-your-domain.com)                                                         |

# Payments --> #18
# Mirroring -> #19
# Workers --> #20
# Event limits --> #21
# Subscriptions --> #22
# Messages --> #23
# Admission check (unsure what this means atm) -> #24

**Comment by rikmeijer** [comment]
Closing this for now, when the related issued are solved, we can determine is there is still anything missing
